cc_library(
    name = "fileio",
    hdrs = ["fileio.hpp"],
    srcs = ["fileio.cpp"],
    deps = [
        "//src/fileio/resmgr",
        "//src/fileio/resmgr:res_cursor",
        "//src/fileio/resmgr:res_font",
        "//src/fileio/resmgr:res_image",
        "//src/fileio/resmgr:res_sound",
        "//src/fileio/resmgr:res_strings",
    ],
    visibility = ["//visibility:public"],
)
