cc_library(
    name = "tinyxml",
    hdrs = [
        "ticpp.h",
        "ticppapi.h",
        "ticpprc.h",
        "tinystr.h",
        "tinyxml.h",
    ],
    srcs = [
        "tinyxml.cpp",
        "ticpp.cpp",
        "tinystr.cpp",
    ],
    visibility = ["//visibility:public"],
)
