cc_library(
    name = "tinyxml",
    hdrs = [
        "ticpp.h",
        "ticppapi.h",
        "ticpprc.h",
        "tinyprint.h",
        "tinystr.h",
        "tinyxml.h",
    ],
    srcs = [
        "ticpp.cpp",
        "tinyprint.cpp",
        "tinystr.cpp",
        "tinyxml.cpp",
        "tinyxmlerror.cpp",
        "tinyxmlparser.cpp",
    ],
    visibility = ["//visibility:public"],
    copts = ["-DTIXML_USE_TICPP"],
)
