

cc_library(
    name = "mathutil",
    hdrs = ["mathutil.hpp"],
    srcs = ["mathutil.cpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "util",
    hdrs = ["utility.hpp"],
    srcs = ["utility.cpp"],
    deps = [
        "//src:location",
        "//src/fileio/resmgr:res_strings",
    ],
    visibility = ["//visibility:public"],
)
