cc_library(
    name = "res_cursor",
    hdrs = ["res_cursor.hpp"],
    srcs = ["res_cursor.cpp"],
    deps = [
        ":resmgr",
        "//src/tools:cursors",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "res_font",
    hdrs = ["res_font.hpp"],
    srcs = ["res_font.cpp"],
    deps = [
        ":resmgr",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "res_image",
    hdrs = ["res_image.hpp"],
    srcs = ["res_image.cpp"],
    deps = [
        ":resmgr",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "res_strings",
    hdrs = ["res_strings.hpp"],
    srcs = ["res_strings.cpp"],
    deps = [
        ":resmgr",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "res_sound",
    hdrs = ["res_sound.hpp"],
    srcs = ["res_sound.cpp"],
    deps = [
        ":resmgr",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "resmgr",
    hdrs = ["resmgr.hpp"],
    visibility = ["//visibility:public"],
)
